### ISSUE TITLE
首次启动不成功，自动下载模型和手动下载模型替换都是卡着

### ISSUE THREAD

**Issue by yating1022** [idootop/MagicMirror#2]
系统是windows11，时间超过10分钟

**Comment by idootop** [comment]
关于Windows下无法正常启动，或者启动成功但提示换脸失败的问题，经过排查是因为Windows自带的安全保护程序，会把 python 构建的换脸 server.exe 文件，误识别为不安全的应用然后删除掉了。

解决方案是在 Windows Defender 程序里，把误删的 server.exe 文件还原到原来的位置，然后重新启动应用应该就正常了。

~下个版本我会尝试修复这个误拦截的问题~ (无解，相关 issue: https://github.com/Nuitka/Nuitka/issues/2685#issuecomment-1923357489)

![Snipaste_2024-11-24_21-23-02](https://github.com/user-attachments/assets/d0f5b62d-98b0-44b2-bbc3-f9bf7f63643b)

**Comment by idootop** [comment]
@yating1022 可以下载新版的 server 压缩包试试看在 Windows 11 上能否正常运行，我测试的几台电脑都正常的。 https://github.com/idootop/MagicMirror/releases/tag/server-v2.0.0
