### ISSUE TITLE
换脸失败，没一个成功的

### ISSUE THREAD

**Issue by hbx123** [idootop/MagicMirror#3]
换脸失败，也不知道为什么，没一个换成功的，不知道是图片大小匹配不行还是匹配不了人脸还是什么，一点都用不了的东西

**Comment by idootop** [comment]
你用的是什么系统，截个图看看。

**Comment by idootop** [comment]
关于Windows下无法正常启动，或者启动成功但提示换脸失败的问题，经过排查是因为Windows自带的安全保护程序，会把 python 构建的换脸 server.exe 文件，误识别为不安全的应用然后删除掉了。

解决方案是在 Windows Defender 程序里，把误删的 server.exe 文件还原到原来的位置，然后重新启动应用应该就正常了。

~下个版本我会尝试修复这个误拦截的问题~ (无解，相关 issue: https://github.com/Nuitka/Nuitka/issues/2685#issuecomment-1923357489)

![Snipaste_2024-11-24_21-23-02](https://github.com/user-attachments/assets/d0f5b62d-98b0-44b2-bbc3-f9bf7f63643b)
