### ISSUE TITLE
下载模型成功了，但启动一直卡着，server.exe也在

### ISSUE THREAD

**Issue by qugengting** [idootop/MagicMirror#6]
![image](https://github.com/user-attachments/assets/7a0551db-5c2b-4a95-871f-d41b791a483c)
一直卡在这界面，查看server.exe也在，试了好几次了都在启动界面
![image](https://github.com/user-attachments/assets/3d2370cf-752b-4633-aa78-bb63a11eb08c)

**Comment by idootop** [comment]
手动双击运行 server.exe 文件，然后检查：
1. 任务管理器中是否有 server.exe 进程
2. 浏览器访问 http://localhost:8023 查看是否有 MagicMirror 提示

<img width="581" alt="图片" src="https://github.com/user-attachments/assets/d062bf0d-3063-414a-a0e6-e8a3a4ebdb21" />

如果上面两项检查结果都是没有，则说明 Python 端 server 启动异常。

这种情况一般是你的电脑环境和 server.exe 有冲突不兼容，无法正常使用本应用。

推荐使用其他换脸应用，比如 [TinyFace](https://github.com/idootop/TinyFace)（MagicMirror 底层使用的 Python 换脸库） 或 [FaceFusion](https://github.com/facefusion/facefusion)。

**Comment by qugengting** [comment]
> 手动双击运行 server.exe 文件，然后检查：
> 
> 1. 任务管理器中是否有 server.exe 进程
> 2. 浏览器访问 http://localhost:8023 查看是否有 MagicMirror 提示
> 
> <img alt="图片" width="581" src="https://private-user-images.githubusercontent.com/35302658/398388678-d062bf0d-3063-414a-a0e6-e8a3a4ebdb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTIzMDYsIm5iZiI6MTczNTA5MjAwNiwicGF0aCI6Ii8zNTMwMjY1OC8zOTgzODg2NzgtZDA2MmJmMGQtMzA2My00MTRhLWEwZTYtZThhM2E0ZWJkYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDAyMDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OTYwOTM0MGExNTBkYWE3NTNhZGI5ODg4MzlkYjhjZTU0NzRjNTk1N2E2YzJhM2Q5ZDJhZjUxNjAwNTFiOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CW_8C9-vJQFCWiid-vCuM36-Qi3Ne5yvdHd6YKnfLm8">
> 如果上面两项检查结果都是没有，则说明 Python 端 server 启动异常。
> 
> 这种情况一般是你的电脑环境和 server.exe 有冲突不兼容，无法正常使用本应用。
> 
> 推荐使用其他换脸应用，比如 [TinyFace](https://github.com/idootop/TinyFace)（MagicMirror 底层使用的 Python 换脸库） 或 [FaceFusion](https://github.com/facefusion/facefusion)。

真的都没有，好的，感谢！

**Comment by idootop** [comment]
@qugengting 更新了一版，你可以试试看下载最新的 server 压缩包，然后解压覆盖原来的，看看能否正常启动。https://github.com/idootop/MagicMirror/releases/tag/server-v2.0.0

**Comment by qugengting** [comment]
> @qugengting 更新了一版，你可以试试看下载最新的 server 压缩包，然后解压覆盖原来的，看看能否正常启动。https://github.com/idootop/MagicMirror/releases/tag/server-v2.0.0

还是不行，估计是公司电脑被限制了，我家里的电脑一下就可以了

**Comment by zyang820** [comment]
> 手动双击运行 server.exe 文件，然后检查：
> 
> 1. 任务管理器中是否有 server.exe 进程
> 2. 浏览器访问 http://localhost:8023 查看是否有 MagicMirror 提示
> 
> <img alt="图片" width="581" src="https://private-user-images.githubusercontent.com/35302658/398388678-d062bf0d-3063-414a-a0e6-e8a3a4ebdb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA0MTcxMDYsIm5iZiI6MTc0MDQxNjgwNiwicGF0aCI6Ii8zNTMwMjY1OC8zOTgzODg2NzgtZDA2MmJmMGQtMzA2My00MTRhLWEwZTYtZThhM2E0ZWJkYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI0VDE3MDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YWM5OGNkNWQ4MTA0NDY3NTVlNTk4NzYyMzdmNGZhYTBjZGJjZmYyZWY1Mzc5NzA0NTEzMjcwODMyMGZmNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z4jmDHSOhxNdOfnNR1zENJzrZdMYm9yYeI8s64E-3O4">
> 如果上面两项检查结果都是没有，则说明 Python 端 server 启动异常。
> 
> 这种情况一般是你的电脑环境和 server.exe 有冲突不兼容，无法正常使用本应用。
> 
> 推荐使用其他换脸应用，比如 [TinyFace](https://github.com/idootop/TinyFace)（MagicMirror 底层使用的 Python 换脸库） 或 [FaceFusion](https://github.com/facefusion/facefusion)。

两个都在但是卡在百分之0是怎么回事

**Comment by idootop** [comment]
@zyang820 内部的下载器默认没有走系统设置的代理，需要你的路由器开全局的透明代理。

建议按照 FAQ 里的说明，在 GitHub 人 release 手动下载 server 压缩包解压初始化。
