### ISSUE TITLE
Mac无法启动

### ISSUE THREAD

**Issue by fairyeye** [idootop/MagicMirror#8]
卡在启动中

系统：MacOS 14.5 (23F79)   Inter芯片  13-inch, 2020

执行MagicMirror下的server.bin报错：bad CPU type in executable

下载的是server_macos_x86_64.zip
file server.bin                                           
server.bin: Mach-O 64-bit executable arm64

老大你是不是打错包了。。。

**Comment by idootop** [comment]
额，我是在 Github Actions 上打包的，手边没 x64 的 macOS 测试。

Anyway 多谢反馈。你可以先用 [CLI](https://github.com/idootop/TinyFace) 版本，或者试试看 [FaceFusion](https://github.com/facefusion/facefusion)。

有时间我会再看一下打包编译的问题，在更多的设备上测试试用。

**Comment by idootop** [comment]
@fairyeye server v2.0.0 已经修复了 https://github.com/idootop/MagicMirror/releases/tag/server-v2.0.0

重新下载一下 server 压缩包，然后解压覆盖即可。

**Comment by flyuuo9** [comment]
@idootop 大佬 mac 10 Mojave  启动界面看不见，也没有报错提示，应该看哪个地方的日志排查？

**Comment by idootop** [comment]
> @idootop 大佬 mac 10 Mojave 启动界面看不见，也没有报错提示，应该看哪个地方的日志排查？

你的 macOS 版本太低了，目前最低支持 macOS 13 Ventura

**Comment by flyuuo9** [comment]
> > @idootop 大佬 mac 10 Mojave 启动界面看不见，也没有报错提示，应该看哪个地方的日志排查？
> 
> 你的 macOS 版本太低了，目前最低支持 macOS 13 Ventura

@idootop  感谢解答，我换了一个win10电脑，卡在"首次加载较慢"提示这里，手动运行server.exe  8023服务未起来。如何排查呢

**Comment by idootop** [comment]
@flyuuo9  目测构建产物不兼容你的电脑环境，需要看下具体原因。你可以在我[公众号](https://del.wang/about)后台留一下你的联系方式，有时间帮你远程看下。
